// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCc5-qmz5_YxhvN-mpiaZMBGkMhHDsrG4c',
    appId: '1:275282326101:web:50f005da55849ad31c5adc',
    messagingSenderId: '275282326101',
    projectId: 'instagram-clone-3ff1c',
    authDomain: 'instagram-clone-3ff1c.firebaseapp.com',
    storageBucket: 'instagram-clone-3ff1c.appspot.com',
    measurementId: 'G-Y0BHT6QPRX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBngXsKlwZUhtxohxEJVRa7gjuzclciIpk',
    appId: '1:275282326101:android:5926797dbf838d931c5adc',
    messagingSenderId: '275282326101',
    projectId: 'instagram-clone-3ff1c',
    storageBucket: 'instagram-clone-3ff1c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwTUNUEJCx455mT8Ypq1cydr5TkpU-oj4',
    appId: '1:275282326101:ios:f4df7c62907b2e2a1c5adc',
    messagingSenderId: '275282326101',
    projectId: 'instagram-clone-3ff1c',
    storageBucket: 'instagram-clone-3ff1c.appspot.com',
    iosClientId: '275282326101-l1ub7ss02mqnkhgrfvlr8g0kdflkmge7.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwTUNUEJCx455mT8Ypq1cydr5TkpU-oj4',
    appId: '1:275282326101:ios:f4df7c62907b2e2a1c5adc',
    messagingSenderId: '275282326101',
    projectId: 'instagram-clone-3ff1c',
    storageBucket: 'instagram-clone-3ff1c.appspot.com',
    iosClientId: '275282326101-l1ub7ss02mqnkhgrfvlr8g0kdflkmge7.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );
}
